version: '3.8'
services:
  db:
    image: postgres:13.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=vivy
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data

  url-service:
    container_name: url-service
    image: vivy/url-service:latest
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://host.docker.internal:5432/vivy
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: postgres
      SPRING_LIQUIBASE_URL: jdbc:postgresql://host.docker.internal:5432/vivy
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres
volumes:
  db:
    driver: local